### ISSUE TITLE
can not compile moneyger4u under centos with maven package

### ISSUE THREAD

**Issue by cloudtrends** [making/moneyger4u#1]
can not compile moneyger4u under centos with maven package

java version is 1.7

[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (copy-resources) @ moneyger4u ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- apt-maven-plugin:1.0.9:process (default) @ moneyger4u ---
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:90: error: ')' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                              ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:90: error: ';' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                               ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:90: error: not a statement
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:90: error: ';' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                         ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:90: error: illegal start of expression
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                                 ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:90: error: ';' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                                                                                 ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeController.java:145: error: illegal start of expression
                .filter(x -> Objects.equals(parentOutcomeCategoryId, x.getParentOutcomeCategoryId()))
                           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/calendar/CalendarController.java:126: error: illegal start of expression
                .map(x -> new GraphData(x.getParentOutcomeCategory().getCategoryName(), x.getAmount()))
                        ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:52: error: illegal start of expression
        outcomes.forEach(outcome -> {
                                  ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:52: error: illegal start of expression
        outcomes.forEach(outcome -> {
                                    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:52: error: ';' expected
        outcomes.forEach(outcome -> {
                                     ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:53: error: not a statement
            if (outcome.getCreatedAt() == null) {
               ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:53: error: ';' expected
            if (outcome.getCreatedAt() == null) {
                                               ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:59: error: illegal start of type
        });
         ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:60: error: <identifier> expected
        dailyOutcomeRepository.save(outcomes);
                                   ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:60: error: <identifier> expected
        dailyOutcomeRepository.save(outcomes);
                                            ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:64: error: class, interface, or enum expected
    public void delete(Integer dailyOutcomeId) {
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:66: error: class, interface, or enum expected
        dailyOutcomeRepository.delete(dailyOutcomeId);
        ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:67: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:71: error: class, interface, or enum expected
    public List<DailyOutcome> findFamilyDailyOutcomeByUserAndDate(User user,
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:75: error: class, interface, or enum expected
        return outcomes;
        ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:76: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:80: error: class, interface, or enum expected
    public List<DailyOutcome> findFamilyDailyOutcomeLikeOutcomeName(
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:85: error: class, interface, or enum expected
        return outcomes;
        ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:86: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:90: error: class, interface, or enum expected
    public List<DailyOutcome> findFamilyDailyOutcomeByParentCategory(Integer parentOutcomeCategoryId, User user, DateTime start, DateTime end) {
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:93: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:97: error: class, interface, or enum expected
    public List<DailyOutcomeReportGroupByOutcomeDate> findFamilyReportGroupByOutcomeDate(
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:101: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:105: error: class, interface, or enum expected
    public List<DailyOutcomeReportGroupByParentOutcomeCategoryId> findFamilyReportGroupByParentOutcomeCategoryId(
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:110: error: class, interface, or enum expected
        for (DailyOutcomeReportGroupByParentOutcomeCategoryId report : result) {
        ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:112: error: class, interface, or enum expected
        }
        ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:114: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:118: error: class, interface, or enum expected
    public Number findFamilyWasteTotal(User user, DateTime start, DateTime end) {
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:121: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:125: error: class, interface, or enum expected
    public DailyOutcomeSearchResult search(DailyOutcomeSearchCriteria criteria,
           ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeServiceImpl.java:128: error: class, interface, or enum expected
    }
    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeExcelImportController.java:44: error: ')' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                              ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeExcelImportController.java:44: error: ';' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                               ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeExcelImportController.java:44: error: not a statement
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeExcelImportController.java:44: error: ';' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                         ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeExcelImportController.java:44: error: illegal start of expression
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                                 ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/app/daily_outcome/DailyOutcomeExcelImportController.java:44: error: ';' expected
                .collect(Collectors.toMap(User::getUserId, user -> user.getLastName() + " " + user.getFirstName()));
                                                                                                                 ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:35: error: illegal start of expression
                        .flatMap(p -> p.getDailyOutcomeCategoryList().stream())
                                    ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:36: error: illegal start of expression
                        .collect(Collectors.toMap(c -> c.getParentOutcomeCategoryId().getCategoryName() + "/" + c.getCategoryName(),
                                                     ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:45: error: illegal start of expression
                .collect(Collectors.toMap(cell -> ColumnLabel.valueOf(cell.getStringCellValue().trim()), Cell::getColumnIndex));
                                                ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:45: error: ')' expected
                .collect(Collectors.toMap(cell -> ColumnLabel.valueOf(cell.getStringCellValue().trim()), Cell::getColumnIndex));
                                                                                                             ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:45: error: ';' expected
                .collect(Collectors.toMap(cell -> ColumnLabel.valueOf(cell.getStringCellValue().trim()), Cell::getColumnIndex));
                                                                                                              ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:45: error: not a statement
                .collect(Collectors.toMap(cell -> ColumnLabel.valueOf(cell.getStringCellValue().trim()), Cell::getColumnIndex));
                                                                                                               ^
/opt/usr/sourcecode/moneyger4u/src/main/java/moneyger4u/domain/service/outcome/DailyOutcomeExcelMapper.java:45: error: ';' expected
                .collect(Collectors.toMap(cell -> ColumnLabel.valueOf(cell.getStringCellValue().trim()), Cell::getColumnIndex));
                                                                                                                             ^
50 errors

**Comment by making** [comment]
Moneyger4u requires Java 8.
